spring:
  datasource:
    username: spring-admin
    password: admin@20
    url: jdbc:mysql://localhost:3306/spring
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
